Book.Website/Models/BookDto.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Book.WebSite.Models;

public class BookDto
{
    [HiddenInput(DisplayValue = false)]
    public string ProductCode { get; set; }
    
    [Required]
    [DisplayName("Title")]
    public string Title { get; set; }

    [Required]
    [DisplayName("Author")]
    public string AuthorName { get; set; }

    [Required]
    [DisplayName("Publisher")]
    public string PublisherName { get; set; }

    [Required]
    [Range(1000, 2100, ErrorMessage = "Publication year must be between 1000 and 2100")]
    [DisplayName("Publication Year")]
    public int PublicationYear { get; set; }
    
    public string Genre { get; set; }
    
    private static readonly string[] genres = new[]
    {
        "Science Fiction", "Mystery", "Romance", "Fantasy", "Thriller"
    };

    private static readonly SelectListItem blankSelectListItem = new SelectListItem("select...", String.Empty);
    public static IEnumerable<SelectListItem> ListGenres(string selectedGenre) {
        var items = new List<SelectListItem> { blankSelectListItem };
        items.AddRange(genres.Select(c => new SelectListItem(c, c, c == selectedGenre)));
        return items;
    }
}

Book.Website/Models/ErrorViewModel.cs
namespace Book.WebSite.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Book.Website/Controllers/BooksController.cs
using BookRetail_API.Models;
using BookRetail_API.Data;
using Book.WebSite.Models;
using Microsoft.AspNetCore.Mvc;

namespace Book.WebSite.Controllers;

public class BooksController : Controller {
    private readonly IBookRetailStorage _db;

    public BooksController(IBookRetailStorage db) {
        this._db = db;
    }
    
    public IActionResult Index() {
        var books = _db.ListBooks();
        
        return View(books);
    }

    public IActionResult Details(string id) {
        var books = _db.FindBook(id);
        
        return View(books);
    }

    [HttpGet]
    public IActionResult Advertise(string id) {
        var booksModel = _db.FindModel(id);
        
        var dto = new BookDto() {
            ProductCode = booksModel.Code,
            PublisherName = $"{booksModel.Publisher.Name} {booksModel.Code}"
        };
        
        return View(dto);
    }

    [HttpPost]
    public IActionResult Advertise(BookDto dto) {
        var existingBook = _db.FindBook(dto.Title);
        
        if (existingBook != default)
            ModelState.AddModelError(nameof(dto.Title),
                "That title is already listed in our database.");
        
        var bookModel = _db.FindModel(dto.ProductCode);
        
        if (bookModel == default) {
            ModelState.AddModelError(nameof(dto.ProductCode),
                $"Sorry, {dto.ProductCode} is not a valid model code.");
        }
        if (!ModelState.IsValid) return View(dto);
        
        var book = new BookRetail_API.Models.Book() {
            Title = dto.Title,
            Genre = dto.Genre,
            BookModel = bookModel,
            PublicationYear = dto.PublicationYear,
            Author = dto.AuthorName,
            ProductCode = dto.ProductCode
        };
        
        _db.CreateBook(book);
        return RedirectToAction("Details", new { id = book.Title });
    }
}

Book.Website/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Book.WebSite.Models;

namespace Auto.WebSite.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Book.Website/Controllers/ModelsController.cs
using BookRetail_API.Data;
using Microsoft.AspNetCore.Mvc;

namespace Book.WebSite.Controllers;

public class ModelsController : Controller {
    private readonly IBookRetailStorage _db;

    public ModelsController(IBookRetailStorage db) {
        this._db = db;
    }

    public IActionResult Books(string id) {
        var model = _db.ListModels().FirstOrDefault(m => m.Code == id);
        return View(model);
    }

    public IActionResult Index() {
        var models = _db.ListModels();
        return View(models);
    }
}

Book.Website/Controllers/PublishersController.cs
using Microsoft.AspNetCore.Mvc;
using BookRetail_API.Data;

namespace Book.WebSite.Controllers;

public class PublishersController : Controller {
    private readonly IBookRetailStorage _db;

    public PublishersController(IBookRetailStorage db) {
        this._db = db;
    }
    public IActionResult Index() {
        var books = _db.ListPublishers();
        return View(books);
    }

    public IActionResult Models(string id) {
        var publisher = _db.ListPublishers().FirstOrDefault(m => m.Code == id);
        return View(publisher);
    }
}

Book.Website/Views/Books/Advertise.cshtml
@using Book.WebSite.Models
@model Book.WebSite.Models.BookDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<h4>Advertise a vehicle for sale</h4>
<form asp-action="Advertise" asp-controller="Books" method="POST" id="advertise-vehicle-form">
    @Html.HiddenFor(model => model.ProductCode)
    Make &amp; Model: @Html.DisplayFor(model => model.ProductCode)
    <hr />
    <p>
        @Html.LabelFor(model => model.Title)
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
    </p>
    <p>
        @Html.LabelFor(model => model.PublicationYear)
        @Html.EditorFor(model => model.PublicationYear)
        @Html.ValidationMessageFor(model => model.PublicationYear)
    </p>
    <p>
        @Html.LabelFor(model => model.Genre)
        @Html.DropDownListFor(model => model.Genre, BookDto.ListGenres(Model.Genre))
        @Html.ValidationMessageFor(model => model.Genre)
    </p>
    <p>
        @Html.LabelFor(model => model.AuthorName)
        @Html.DropDownListFor(model => model.AuthorName, BookDto.ListGenres(Model.AuthorName))
        @Html.ValidationMessageFor(model => model.AuthorName)
    </p>
    <input type="submit" value="Advertise!" />
</form>

Book.Website/Views/Books/Details.cshtml
@model BookRetail_API.Models.Book
@{
    ViewData["Title"] = $"{Model.Title} : Book";
}
<h1>@Model.Title</h1>
<hr />
<dl>
    <dt>Publishers:</dt>
    <dd><a href="@Url.Action("Models", "Publishers", new { id = Model.BookModel.PublisherCode})">@Model.BookModel.Publisher.Name</a></dd>
    <dt>Model:</dt>
    <dd>@Model.BookModel.Code</dd>
    <dt>Year:</dt>
    <dd>@Model.PublicationYear</dd>
    <dt>Genre:</dt>
    <dd>@Model.Genre</dd>
    <dt>Author:</dt>
    <dd>@Model.Author</dd>
</dl>

Book.Website/Views/Books/Index.cshtml
@model IEnumerable<BookRetail_API.Models.Book>
@{
    ViewBag.Title = "Publishers";
}

<ul>
    @foreach (var book in Model) {
        <li>
            <a href="@Url.Action("Details", "Books", new { id = book.Title })">@book.Title</a>
        </li>
    }
</ul>

Book.Website/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Book Retail!</h1>
    <p>The sample app.</p>
</div>

Book.Website/Views/Models/Books.cshtml
@model BookRetail_API.Models.ProductModel

<h1>@Model.Publisher.Name @Model.Code</h1>
<hr />
@if (Model.Books.Any()) {
    <ul>
        @foreach (var book in Model.Books) {
            <li><a href="@Url.Action("Details", "Books", new { id = book.Title})">@book.Title</a></li>
        }
    </ul>
} else {
    <p><em>We don't have any @Model.Publisher.Name @Model.Code books for sale right now.</em></p>
}
<hr />
<a href="@Url.Action("Advertise", "Books" , new { id = @Model.Code })">Sell your @Model.Publisher.Name @Model.Code here</a>

Book.Website/Views/Models/Index.cshtml
@model System.Collections.Generic.IEnumerable<BookRetail_API.Models.ProductModel>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>All Models</h2>
@foreach (var group in Model.GroupBy(m => m.Publisher).OrderBy(m => m.Key.Name)) {
    <h3>@group.Key.Name</h3>
    <ul>
        @foreach (var bookModel in group) {
            <li>
                <a href="@Url.Action("Books", "Models", new {id = bookModel.Code})">
                    @bookModel.Publisher.Name @bookModel.Code
                </a>
            </li>
        }
    </ul>
}

Book.Website/Views/Publishers/Index.cshtml
@model System.Collections.Generic.IEnumerable<BookRetail_API.Models.Publisher>

@{
    ViewBag.Title = "Publishers";
}

<h2>Publishers</h2>
<ul>
    @foreach (var pbsher in Model) {
        <li><a href="@Url.Action("Models", "Publishers", new { id = pbsher.Code })">@pbsher.Name</a></li>
    }
</ul>

Book.Website/Views/Publishers/Models.cshtml
@model BookRetail_API.Models.Publisher

@{
    ViewBag.Title = Model.Name;
    Layout = "_Layout";
}

<h2>@Model.Name</h2>
<h4>Currently listed for sale:</h4>
<ul>
    @foreach (var bookModel in Model.Models.Where(m => m.Books.Count > 0)) {
        <li>
            @bookModel.Code
            <a href="@Url.Action("Books", "Models", new { id = bookModel.Code })">view @bookModel.Books.Count books</a>
        </li>
    }
</ul>
<h4>Other models:</h4>
<ul>
    @foreach (var bookModel in Model.Models.Where(m => m.Books.Count == 0)) {
        <li>
            <a href="@Url.Action("Books", "Models", new { id = bookModel.Code })">@bookModel.Code</a>
        </li>
    }
</ul>

Book.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Book</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book Retail</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publishers" asp-action="Index">Publishers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Models" asp-action="Index">Product Models</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">All Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div id="signalr-notifications"></div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Book Retail App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.3/signalr.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>